config/routes.rb
Rails.application.routes.draw do
  get 'reviews/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'lists#index'

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  DEFAULT_IMG = "https://images.unsplash.com/photo-1585647347129-7aebb8689a78?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1887&q=80"
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list

  validates :comment, :rating, presence: true
  validates :rating, numericality: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path, status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    # Empty instance for simple_form
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @review = Review.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @list = List.find(params[:list_id])

    @review.list = @list

    if @review.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie, collection: Movie.all, prompt: "Choose a movie" %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>New Bookmark</h1>
  <%= render "form" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPracticeWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/shared/nav" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_nav.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fa-solid fa-ticket"></i>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
              <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Home", root_path, class: "dropdown-item" %>
              <a class="dropdown-item" href="#">Add List</a>
            </div>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div class="container">
  <h1>All the lists</h1>

  <ul class="list-inline tabs-underlined">
    <li>
      <%= link_to "See Lists", lists_path, class: "tab-underlined active" %>
    </li>
    <li>
      <%= link_to "Add a list", new_list_path, class: "tab-underlined" %>
    </li>
  </ul>

  <div class="cards" id="lists" data-movies-target="lists"
    data-controller="sortable">
    <% @lists.each do |list| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= List::DEFAULT_IMG %>)">
        <h2><%= list.name %></h2>
            <%= link_to list_path(list) do %>
              <button class="btn btn-primary">
                <i class="fa-solid fa-eye"></i>
              </button>
            <% end %>
            <button class="btn btn-danger text-white">
              <i class="fa-solid fa-trash-can"></i>
            </button>
      </div>
    <% end %>
  </div>

</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>New List:</h1>
  <%= render "form" %>
</div>

app/views/lists/show.html.erb
<div class="container mt-1">
  <div class="row">
    <div class="col-10">
      <h1><%= @list.name %></h1>
    </div>
    <div class="col-2 d-flex align-items-center">
      <%= link_to new_list_bookmark_path(@list) do %>
        <button class="btn btn-primary"><i class="fa-solid fa-plus"></i></button>
      <% end %>
    </div>
  </div>

  <div class="cards">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card-product d-flex justify-content-between">
        <img src="<%= bookmark.movie.poster_url %>"/>

        <div class="card-product-infos w-75">
          <h2><%= bookmark.movie.title %></h2>
          <p><%= bookmark.movie.rating %> / 10</p>
        </div>

        <div class="p-5">
          <%= link_to bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Do you really want to delete #{bookmark.movie.title}"}, class: "fs-3 text-danger" do %>
            <i class="fa-solid fa-circle-xmark"></i>
          <% end %>
        </div>

      </div>
    <% end %>
  </div>

  <div class="row mt-2">
    <h3>Reviews</h3>
    <div class="reviews col-6">
      <% @list.reviews.each do |review| %>
      <div class="review">
          <i class="fa-solid fa-comment"></i>
          <div class="review-content">
            <p><%= review.comment %></p>
            <p>
            <% review.rating.times do %>
              <i class='fa-solid fa-star text-warning'></i>
            <% end %>
            </p>
            <p><%= distance_of_time_in_words_to_now(review.created_at) %></p>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col-6 border rounded h-25 p-2 bg-light bg-gradient">
      <div class="review-form">
        <%= simple_form_for [@list, @review] do |f| %>
          <%= f.input :comment %>
          <%= f.input :rating, collection: (1..5).to_a, label: "Rate this list", input_html: {data: {controller: "star-rating"}} %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>